[package]
name = "fetchy"
version = "0.1.0"
edition = "2021"

[dependencies.js-sys]
version = "0.3"

[dependencies.pasts]
version = "0.11"
features = ["web"]

[dependencies.wasm-bindgen]
version = "0.2"

[dependencies.wasm-bindgen-futures]
version = "0.4"

[dependencies.web-sys]
version = "0.3"
features = [
    "console",
    "Document",
    "Element",
    "Headers",
    "ReadableStream",
    "Response",
    "Request",
    "RequestInit",
    "Window",
]
